spring.application.name=ZeroTraceSpringBoot

# Database Connection (SQLite)
spring.datasource.url=jdbc:sqlite:mail.db?journal_mode=WAL&busy_timeout=5000&date_class=TEXT&date_string_format=yyyy-MM-dd HH:mm:ss
spring.datasource.driver-class-name=org.sqlite.JDBC

# Spring Batch Schema Initialization & Lifecycle
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# Auto-initialize user schema and data on startup
spring.sql.init.mode=always

# Localized Messages Configuration
spring.messages.basename=message
spring.messages.encoding=UTF-8

# Logging Configuration
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.rabbit=DEBUG

# Mail Scheduler Configuration (Set to run every 10 minutes from 8AM to 11PM on weekdays)
mail.scheduler.cron=0 */10 8-23 * * MON-FRI
