# SMTP 服务器地址 (如: email-smtp.us-east-1.amazonaws.com)
mail.smtp.host=smtp.gmail.com

# SMTP 服务端口 (常用的有: 25, 465, 587)
mail.smtp.port=465

# SMTP 用户名 (对于 Amazon SES，为您的 SMTP 凭证用户名)
mail.smtp.username=testuser@example.com

# SMTP 密码 (对于 Amazon SES，为您的 SMTP 凭证密码)
# SMTP 密码 (对于 gmail是授权码)
mail.smtp.password=testpass

# 是否启用 STARTTLS 加密 (默认为 true)
mail.smtp.starttls.enable=true

# 是否直接启用 SSL/TLS 加密 (默认为 false，若端口为 465，请将其设置为 true)
mail.smtp.ssl.enable=true

# Socket 连接超时时间，单位为毫秒 (默认 5000 毫秒)
mail.smtp.connectiontimeout=5000

# Socket 读取超时时间，单位为毫秒 (默认 5000 毫秒)
mail.smtp.timeout=5000

# Socket 写入超时时间，单位为毫秒 (默认 5000 毫秒)
mail.smtp.writetimeout=5000

# 是否启用调试模式 (默认为 false)
mail.debug=false

# 发件人名称
mail.smtp.sender.name=Fei Long Lab

# 发送者邮箱
mail.smtp.sender.email=testuser@example.com

# SMTP服务器连接调试标志：1(表示开启（会拦截连接）)，0(表示关闭（会真实连接）)
mail.smtp.debug.flag=1

# SMTP发送失败调试标志：1(表示开启（会输出错误信息）)，0(表示关闭（不会输出错误信息）)
mail.smtp.send.debug.flag=0
